### ISSUE TITLE
Export Data Preview

### ISSUE THREAD

**Issue by mattdrake08** [fraxiinus/ReplayBook#100]
**Describe the bug**
The preview on export data is not always reflective of what is selected. Boxes selected are still exported properly, but the preview is not correct.

**To Reproduce**
1. Go to 'Export Data'
2. Right Click on second selection box
3. Click 'Select All'
4. Right Click on third selection box
5. Click 'Select All'
6. Preview does not reflect all boxes checked

**Expected behavior**
Preview correctly shows what items are selected

**Screenshots**
![image](https://user-images.githubusercontent.com/70590748/135139585-bea6ecaa-f164-4b44-bb49-ef2aa07ecf8b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by fraxiinus** [comment]
I'm currently reworking the exporter, I'll make sure the new one won't have this bug

**Comment by fraxiinus** [comment]
New exporter released https://github.com/fraxiinus/ReplayBook/releases/tag/1.4.0
