### ISSUE TITLE
Crash when loading or downloading thumbnails.

### ISSUE THREAD

**Issue by JerryLiew** [fraxiinus/ReplayBook#127]
This problem has occurred several times, but I can't reproduce it exactly. According to the debugging information, I guess it is caused by incorrectly traversing a collection when downloading thumbnails, such as deleting elements when traversing the collection.
screenshot:
![image](https://user-images.githubusercontent.com/51161678/143874573-2f147f1e-65cd-4f0a-9ae6-52619f720b11.png)
log:
[ReplayBookLog_20211129_2059.log](https://github.com/fraxiinus/ReplayBook/files/7618367/ReplayBookLog_20211129_2059.log)

**Comment by fraxiinus** [comment]
The whole image downloading system is such a mess. I will investigate what is happening.
