### ISSUE TITLE
Exporter using the wrong background color

### ISSUE THREAD

**Issue by mattdrake08** [fraxiinus/ReplayBook#152]
**Describe the bug**
User interface changing displayed information based on window size.

**To Reproduce**
1. Click on '....'
2. Click on 'Export Data...'
3. Click on 'Show advanced mode'
4. Extend window length
5. Data preview section pops up

**Expected behavior**
Data preview section to already be there/existence not dependent on window size

**Screenshots**
![image](https://user-images.githubusercontent.com/70590748/152040020-2fb7c97a-add4-4377-8b14-6d2b8bc1c7c9.png)
![image](https://user-images.githubusercontent.com/70590748/152039983-433f52d4-8d6d-4446-a749-d3f76c42f8f8.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by fraxiinus** [comment]
Hello

This is intended behavior. The smaller size doesn't fit the data preview.

https://www.fraxiinus.dev/ReplayBook/tutorial/4_export_data.html

**Comment by fraxiinus** [comment]
What is not intended is the background colors of the exporter. It should not be that dark. 

Reworking this story to cover that visual bug
