### ISSUE TITLE
Add support for Chinese locale replay (By add -Locale=zh_CN command arg)

### ISSUE THREAD

**Issue by Nsiso** [fraxiinus/ReplayBook#171]
Please add support for Chinese replay.
You could simply check the env locale and add the local command argument in League client.

**Comment by Nsiso** [comment]
command argument: -Locale=(Any)

**Comment by fraxiinus** [comment]
Hello!
This is being done already: check this discussion thread: #132 

You can set the locale command argument in the executable edit window.

**Comment by Nsiso** [comment]
> Hello! This is being done already: check this discussion thread: #132
> 
> You can set the locale command argument in the executable edit window.

Thanks a lot! It's working! I hope it could auto detect local prop~ Have a nice day!

**Comment by Nsiso** [comment]
Closing this issue.
