### ISSUE TITLE
LiteDB ENSURE: slot length must be empty before use

### ISSUE THREAD

**Issue by cjpwnzyou** [fraxiinus/ReplayBook#184]
Getting this error message when loading replays after newest update.

**Comment by fraxiinus** [comment]
when you get this error, do any replays appear in the list? or no replays at all.

**Comment by fraxiinus** [comment]
One month with no clarification. Users should try clearing the replay cache (Settings->Replays->Clear cache) and restarting the application.
If the error continues, but other replays are loading, you may just have a corrupted file that cannot be read.
