### ISSUE TITLE
Downloading wrong static data version

### ISSUE THREAD

**Issue by ShadowHazel** [fraxiinus/ReplayBook#241]
**Describe the bug**
When downloading a Static Data Bundle for version X.Y.Z where Y is a single digit number, it downloads the most recent version in which that single digit number is the first digit in Y. Such as selecting 10.1.1 and it gives you 1.19.1 or selecting 12.2.1 and it gives you 12.23.1

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Static Data'
3. Click on 'Add'
4. Scroll down to '10.1.1'
5. Click on 'Download'
6. See '10.19.1' is downloaded

**Expected behavior**
The exact Static Data version selected is what is downloaded.

**Desktop:**
 - OS: Windows
 - Replaybook Version: release 1.6.3

**Comment by fraxiinus** [comment]
Weird!
