### ISSUE TITLE
Crashes on particular keys for Export Data Wizard, in this case "PENTA_KILLS"

### ISSUE THREAD

**Issue by ctrlaltdeleon** [fraxiinus/ReplayBook#264]
**Describe the bug**
Using the "Export Data Wizard", trying to export a particular player and a single attribute, specifically "PENTA_KILLS" and pressing next causes ReplayBook to crash. Clicking on something else, for example "ASSISTS" works out fine.

**To Reproduce**
1. Click on "Export Data" for a match. ![1](https://user-images.githubusercontent.com/10361542/235333153-8d0ec1f2-dbbb-4e65-a3a2-3486831a4a77.png) 
2. Start Wizard. ![2](https://user-images.githubusercontent.com/10361542/235333169-d953b5c5-7ef6-40f8-8571-4f80a6e14e5f.png)
3. Click on 1 player with manual selection, press next. ![3](https://user-images.githubusercontent.com/10361542/235333178-cfea1be8-1896-4c38-a192-97ce8ae41fe4.png)
4. Search up "PENTA", check mark the box, press next. ![4](https://user-images.githubusercontent.com/10361542/235333199-520f5e48-3fdc-4efc-ae8c-55b456d3b8cc.png)
5. ReplayBook says "not responding" and crashes afterwards.

**Expected behavior**
In other instances such as the "Advanced Export", this does not crash, so I expected not to crash here either.

**Screenshots**
Above with steps to reproduce.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A
 - Version: 1.6.3

**Comment by fraxiinus** [comment]
This should be fixed in the latest release. I just published it :)

https://github.com/fraxiinus/ReplayBook/releases/tag/1.7.0
