### ISSUE TITLE
1.7.0 Installation Crash on Finish

### ISSUE THREAD

**Issue by ctrlaltdeleon** [fraxiinus/ReplayBook#266]
**Describe the bug**
When installing 1.7.0, during the finish of installation an error pops out. This causes weird behavior with ReplayBook not being able to boot up, being boot up but empty paths to replays, or simply restarting the installation process which was the most common output.

**To Reproduce**
1. Download 1.7.0 zip.
2. Go through install steps.
3. When about to click "Finish", error pops up.
![error](https://user-images.githubusercontent.com/10361542/235345358-41a18c24-e0dc-4eee-91ff-4133450f9e0c.png)

**Expected behavior**
Installation to be fine and boot up ReplayBook as before.

**Screenshots**
Screenshots with steps to reproduce.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A
 - Version: 1.7.0

**Comment by fraxiinus** [comment]
In the ReplayBook directory, delete the 'cache' folder and try again.

**Comment by fraxiinus** [comment]
If that doesn't work, please find and attach the most recent log file:

![explorer_IwbInf1PGe](https://user-images.githubusercontent.com/8365233/235373779-dc2bb1f2-b0a8-4a49-89fe-669739517a4c.png)

![explorer_CwC5PP5nAo](https://user-images.githubusercontent.com/8365233/235373782-e814cbe2-65a6-44d2-bfa2-4a8041d8be9a.png)

**Comment by fraxiinus** [comment]
Fixed in #269
