### ISSUE TITLE
Replay stats and game info missing or incorrect since patch 13.20

### ISSUE THREAD

**Issue by Hyporeal** [fraxiinus/ReplayBook#291]
**Describe the bug**
Replay stats and game info missing or incorrect

**To Reproduce**
1. Download Replay in LoL version 13.20
2. Open ReplayBook
3. Click on ROFL file
4. Incorrect and blank information is visible (Note: replay file plays normally)

**Expected behavior**
Correct and complete replay game info an stats to be displayed.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - ReplayBook Version 1.7.2

**Additional context**
This seems to have started since patch 13.20.

![Screenshot 2023-10-14 143405](https://github.com/fraxiinus/ReplayBook/assets/87534492/038c1197-b97b-40c2-bf32-d8a9780e2b66)
![Screenshot 2023-10-14 143435](https://github.com/fraxiinus/ReplayBook/assets/87534492/e7af99eb-6d0f-4005-b80d-848046860a54)

Note that this was not a Howeling Abyss game.

**Comment by fraxiinus** [comment]
Hi, it appears that in patch 13,20, Riot has stopped populating the required 'statsJson' field. Any replays downloaded for that patch will not have any player data associated with it. Unfortunately I don't know if this is a decision Riot has deliberately made, or if it is just a bug.

https://github.com/fraxiinus/roflxd.cs/issues/4

**Comment by Hyporeal** [comment]
Hi @fraxiinus,

Thank you for your quick response. I've gone ahead and submitted a bug report to Riot regarding the missing 'statsJson' field issue since patch 13.20.

Additionally, I noticed that some websites like leagueofgraphs.com still have detailed game information. It made me wonder if ReplayBook isn't already utilizing Riot's API, it could potentially be an alternative source for the game info and stats that are currently missing. Just a thought!

Looking forward to any updates and really appreciate your dedication!

**Comment by LevinKlust** [comment]
Hi @Hyporeal did you already got an answer?

**Comment by Hyporeal** [comment]
> Hi @Hyporeal did you already got an answer?

Hi there. No, I was not contacted by Riot, if that's what you mean. :)

**Comment by neeemo** [comment]
> Hi @fraxiinus,
> 
> Thank you for your quick response. I've gone ahead and submitted a bug report to Riot regarding the missing 'statsJson' field issue since patch 13.20.
> 
> Additionally, I noticed that some websites like leagueofgraphs.com still have detailed game information. It made me wonder if ReplayBook isn't already utilizing Riot's API, it could potentially be an alternative source for the game info and stats that are currently missing. Just a thought!
> 
> Looking forward to any updates and really appreciate your dedication!

I believe its because leagueofgraphs.com uses the Match api through riot to get their data,
https://developer.riotgames.com/apis#match-v5

Sadly this does not work for custom games, only for games played through ladder. So I'm very much in need of the stats from the replay to be able to showcase stats from our custom tournament games. I do not know if you can fetch stats for games generated through the tournament api though.

**Comment by fraxiinus** [comment]
As of patch 13.22, this issue has been fixed by Riot.
