### ISSUE TITLE
replay doesn't open

### ISSUE THREAD

**Issue by avauk12** [fraxiinus/ReplayBook#314]
something about an unexpected error 
![Capture](https://github.com/user-attachments/assets/a10a87fc-f73f-4eee-8dec-64f5fba410be)

**Comment by fraxiinus** [comment]
You must disable Vanguard before ReplayBook is able to play replays. https://github.com/fraxiinus/ReplayBook/issues/301

If you don't see vgtray, you can try this script https://github.com/Vudgekek/NoMoreVanguard?tab=readme-ov-file

**Comment by avauk12** [comment]
Hi, it the same problem still occurs unfortunately
Thanks for the suggestion though

**Comment by fraxiinus** [comment]
This issue _should_ be fixed in the latest release. Please re-open this issue if you are still experiencing this exact exception.

**Comment by Cische** [comment]
Hi, unfortunately, I am still experiencing the same issue with the latest version 1.7.4. How can I solve it,
![屏幕截图 2024-10-30 221458](https://github.com/user-attachments/assets/a3b9df63-6854-4ec9-ad0d-d6c2369a4f17)

**Comment by Cische** [comment]
> 此问题_应在_最新版本中修复。如果您仍然遇到此确切的异常，请重新打开此问题。

Look forward to your reply
