### ISSUE TITLE
Opening recent replay showing error windows

### ISSUE THREAD

**Issue by lomemori** [fraxiinus/ReplayBook#318]
Hello, I'm currently having this error with recent replays. I did clear cache and was able to play replays before April 2024, but playing the other replays after April won't work but showing this windows. Is it the same problem when vanguard isn't deactivated? 

![fda328463a271b380e2483c2c8dd62ec](https://github.com/user-attachments/assets/5a9be98f-6c9f-4958-8dc5-e36609a995ef)

**Comment by fraxiinus** [comment]
Replays from 14.9 through 14.10 do not contain metadata and are not supported by ReplayBook. It was caused by a change in Riot's replay format.
