### ISSUE TITLE
I moved some replays from one computer to another, but I think they can't be read by ReplayBook

### ISSUE THREAD

**Issue by LuinGa9011** [fraxiinus/ReplayBook#320]
I used to play on a different PC that's now being used by a friend of mine. I moved some of the replays I had on there to my current PC by moving them to a file, compressing it and sending it to myself through an email. I downloaded it into my new pc, booted up ReplayBook and at the top, it says a number of files failed to load. Granted, It's been a long time since I last opened ReplayBook so I'm not sure if this is a result of the transfer or something else happened along the line.
![image_2024-09-25_145326306](https://github.com/user-attachments/assets/6cd2c4ca-2b21-4992-a95f-dd5cccf939c7)

I've cleared the cache and restarted ReplayBook but it always come back with the same problem. I'm not quite sure what it means by "Parameter is incorrect," and, "Arithmetic operation resulted in an overflow." 

Could I get some help with this?

**Comment by fraxiinus** [comment]
If these replays are from 14.9 through 14.10 then they won't have the data required for ReplayBook.

There is also a chance that they were corrupted after downloading. You can try either downloading them again, or transfer them using another method.
