### ISSUE TITLE
Can LeagueDirector and Replaybook be used together? 

### ISSUE THREAD

**Issue by box96** [fraxiinus/ReplayBook#325]
Can LeagueDirector and Replaybook be used together? When I use Replaybook, LeagueDirector cannot detect the client.Is there anyone who has experience using these 2 tools together? Any help would be greatly appreciated，I have the latest client and today's roft file, filled in the code about EnableReplayApi=1, LeagueDirecto just doesn't work

**Comment by fraxiinus** [comment]
Should be possible, I've seen users using them together before. Unfortunately I don't have experience with LeagueDirector so I can't help.
