### ISSUE TITLE
Way To Get Gold Every Second

### ISSUE THREAD

**Issue by ziaoang** [fraxiinus/ReplayBook#59]
Is there any way to get gold for ten players every second in the game?

**Comment by fraxiinus** [comment]
There's no way to get data at a certain time. The closest thing you can get is average gold/second

**Comment by ziaoang** [comment]
In some data website, we can see the gold curve and the exp curve, do you know how can they get these information?

**Comment by fraxiinus** [comment]
That data is coming from Riot Games API and is not available from replays
https://developer.riotgames.com/

**Comment by ziaoang** [comment]
We could play these replayes offline, which means all the game information is included in the replay file. I read the code and find ReplayBook does not get the game state at every game moment, I think maybe the summary data is open for us and the detail data is encrypted, is that right?

**Comment by fraxiinus** [comment]
You got it. The replay data is obfuscated and encrypted, making it practically impossible. Even if you manage to crack it, Riot changes the obfuscation every patch.

**Comment by ziaoang** [comment]
Thanks for your answer 👍
