### ISSUE TITLE
Is there any way to run this on a mac?

### ISSUE THREAD

**Issue by CodyBontecou** [fraxiinus/ReplayBook#60]
Is there any way I can compile the code and run this on my mac?

**Comment by fraxiinus** [comment]
I don't think a Mac port would be that easy. ReplayBook unfortunately was not designed for multi-platform support, so it relies on Windows specific features and functions.

**Comment by CodyBontecou** [comment]
> I don't think a Mac port would be that easy. ReplayBook unfortunately was not designed for multi-platform support, so it relies on Windows specific features and functions.

Could you direct me to the Window's specific code/features/functions?

**Comment by fraxiinus** [comment]
I don't remember exactly where all the Windows specific code is. Best way to find out is to try compiling the code on a Mac.
I do know that the UI is written in WPF, which is a Windows only framework, so a port to any other platform would require a complete rewrite of the UI.

**Comment by CodyBontecou** [comment]
I'm curious if you could walk me through some of the code sometime. I'd love to attempt to build out a Mac (or web if possible) version.

**Comment by fraxiinus** [comment]
If you add me on Discord, we can find a time for me to show you around the code.

https://discord.gg/c33Rc5J
