### ISSUE TITLE
Play Button Disabled

### ISSUE THREAD

**Issue by pnheinsohn** [fraxiinus/ReplayBook#68]
Hi everyone, I've just downloaded ReplayBook and setted it... it finds my replays and show me the stats of them. Also, I have registered 1 executable according to patch 11.11. However, I've got other patches replays but can't play them, nor find them at the LoL website. Is this normal behaviour?

![image](https://user-images.githubusercontent.com/26394046/119731737-4be12800-be45-11eb-9584-0fe54de33178.png)
![image](https://user-images.githubusercontent.com/26394046/119731775-569bbd00-be45-11eb-9093-0e284fbe380e.png)

Ty :)

**Comment by fraxiinus** [comment]
In order to play a replay from 11.10, you need 11.10 registered as an executable in ReplayBook. This is a limitation of Riot's replay system. If you do not have a backup, try looking for a download online, or from someone you know.
