### ISSUE TITLE
Crashes When Trying to Replay Match From 11.12

### ISSUE THREAD

**Issue by mitkan191003** [fraxiinus/ReplayBook#69]
Edit: I looked closer and it seems to be mislabelling 11.12 as 11.8 and 11.4. If so, you can ignore this bug.

**Describe the bug**
I have my league clients on two drives. The current one (11.12) is on my internal drive and the older patches are on a removable drive. When trying to play replay files specifically from patch 11.12, the app refuses to recognize that 11.12 is installed and asks if I want to replay the match using 11.8 or 11.4. It does this while the removable drive is disconnected, meaning that it has access to neither of them. Trying to rescan the directories with my league clients crashes Replaybook. To fix this, I need to connect my external drive and rescan the directories. This bug only appeared on 11.12.

**To Reproduce**
1. Add a secondary drive in the list of Executable Source Folders
2. Disconnect secondary drive
3. Try to replay match from 11.12
4. Try to rescan Folders for Executables

**Expected behavior**
The app should recognize that C:\Riot Games has 11.12 installed and should not ask me which patch to use.

**Screenshots**
![image](https://user-images.githubusercontent.com/76726314/121829796-8b0ad800-cc91-11eb-82e9-45ce86d4d0b5.png)
The patch menu that pops up:
![image](https://user-images.githubusercontent.com/76726314/121829807-95c56d00-cc91-11eb-81eb-82ed0e636a19.png)
The list of directories that I keep my patches in:
![image](https://user-images.githubusercontent.com/76726314/121829833-9fe76b80-cc91-11eb-8615-8235a305755b.png)
The app crashes after clicking the scan Folders for Executables button.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by fraxiinus** [comment]
Thanks for the in-depth bug report. Could you attach the `executablesettings.json` file from the ReplayBook directory?

**Comment by mitkan191003** [comment]
Github doesn't allow .json files here so I uploaded it to Google Drive.
[https://drive.google.com/file/d/1bVT3KxGIFJgRIBNYjsJtwqjIhdFxwksh/view?usp=sharing]()

**Comment by fraxiinus** [comment]
Something unrelated to the crashing bug: It seems you have an executable registered with the name 'Patch 11.4' but the actual patch number is 11.12. Same thing with your 'Patch 11.8'.

```JSON
{
  "name": "Patch 11.4",
  "targetPath": "C:\\Riot Games\\League of Legends\\Game\\League of Legends.exe",
  "startFolder": "C:\\Riot Games\\League of Legends\\Game",
  "patchNumber": "11.12.379.4946",
  ...
},
{
  "name": "Patch 11.8",
  "targetPath": "C:\\Riot Games\\League of Legends (PBE)\\Game\\League of Legends.exe",
  "startFolder": "C:\\Riot Games\\League of Legends (PBE)\\Game",
  "patchNumber": "11.12.379.4946",
  ...
}
```
So ReplayBook was right to ask you which one to use to play a 11.12 replay. However the executables were named in a confusing way that made you think ReplayBook wasn't bringing up the right executables.

I would suggest renaming the executable that will get updated something like 'Live Game' or 'Live Game (PBE)' to not get confused.

**Comment by fraxiinus** [comment]
(Back to the actual bug) The bugfix will probably be something that ignores the directory not found failure and just lets the user know. That way if you remove a drive ReplayBook can continue as normal and the user can re-scan when the drive is re-attached.

**Comment by fraxiinus** [comment]
#70 should resolve the scan crash bug.  Here is what the fix looks like
![image](https://user-images.githubusercontent.com/8365233/122139315-b3700f00-ce16-11eb-9208-62d9da29bab1.png)


You can download the test build here: 
https://github.com/fraxiinus/ReplayBook/actions/runs/941130549
