### ISSUE TITLE
Question about compatibility with other project

### ISSUE THREAD

**Issue by ChronoBrake** [fraxiinus/ReplayBook#74]
Hey,

Quick question. In our project we using system to auto recording all games played with that software https://github.com/1lann/lol-replay

We saw your tool and we trying to run recording replays by lol-replay in ReplayBook, but it's not working :/ In attachments you can look on example recorded game file. Any tips Sir?

Example file: https://easyupload.io/sw5wji

Best regards

**Comment by fraxiinus** [comment]
I am not familiar with that project. I took a quick look at that file, its not a valid ROFL file type so I think you're supposed to use the 'server' package of that project to play the files.

ReplayBook can only deal with ROFL file types
